### PR TITLE
fix: error due to navigator in locale

### LINKED ISSUE #41: Getting this error on localhost:3000
image

### PR DESCRIPTION
**Pull request by pc-beast**
Fixes #41

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Instead, add fromNavigator, and check if locale is among supported locales, and if it isn't, then use fallback locale.

To support locale loading, if a locale like en-GB is not in supported locales, split it by `-` and load only the first part, i.e., `en`

**Comment by iamareebjamal** [comment]
That won't work if I have locale as `ch-ZN`, it'll always load `ch`. It should only split if locale was not found

**Comment by pc-beast** [comment]
@iamareebjamal sir please review

**Comment by pc-beast** [comment]
@mariobehling please review

**Review by hongquan — APPROVED** [review]
Tested on my localhost. It works.

**Review by prateekj117 — APPROVED** [review]
LGTM !!!

**Pull request merged**
