### PR TITLE
chore: setup translations

### LINKED ISSUE #15: Setup translation
Setup translation which best matches our implementation of client side translation of current site with a language switcher.

The solution should provide ways to extract messages from the code and update the translations though CLI

There are multiple options, evaluate and choose:

https://github.com/vercel/next.js/tree/canary/examples/i18n-routing
https://github.com/vercel/next.js/tree/canary/examples/with-i18n-rosetta
https://github.com/vercel/next.js/tree/canary/examples/with-next-i18next
https://github.com/vercel/next.js/tree/canary/examples/with-lingui
https://github.com/vercel/next.js/tree/canary/examples/with-next-translate

### PR DESCRIPTION
**Pull request by pc-beast**
Fixes #15

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Add hindi translations so I can see if it works

**Comment by pc-beast** [comment]
@iamareebjamal done

**Comment by iamareebjamal** [comment]
Why did you remove the autogenerated stuff? Translate that. How am I supposed to test it now?

**Comment by pc-beast** [comment]
i did not removed any autogenerated stuff

**Comment by iamareebjamal** [comment]
Great Job. I have finished the last needed step

**Pull request merged**
