### PR TITLE
Docs:how to install dependencies updated.

### PR DESCRIPTION
**Pull request by iamdevvalecha**
Minor issues with README #75

### CODE REVIEW

**Comment by iamdevvalecha** [comment]
@prateekj117 review.

**Review by Ratheshan03 — DISMISSED** [review]
looks good to me!

**Review by mariobehling — DISMISSED** [review]

**Comment by mariobehling** [comment]
Please resolve merge conflicts.

**Comment by iamdevvalecha** [comment]
@mariobehling sure!

**Pull request closed without merging**
