### PR TITLE
chore: loader bar added

### PR DESCRIPTION
**Pull request by iamdevvalecha**
https://github.com/fossasia/open-event-next/issues/16

### CODE REVIEW

**Comment by iamareebjamal** [comment]
You've undone the styling of the project

**Comment by iamdevvalecha** [comment]
> You've undone the styling of the project

@iamareebjamal okay let me do.

**Comment by iamareebjamal** [comment]
Not what I meant by that

**Comment by iamdevvalecha** [comment]
then?

**Comment by iamdevvalecha** [comment]
as their are some conflicts i am creating different pr.

**Pull request closed without merging**
